---
name: Example Program Tests

on:
  push:


jobs:
  pylint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: pip install coverage flake8 pytest
      - name: Lint
        run: make lint

  dynamic_programming:
    name: Maze Runner (dynamic programming)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent_type: ['v', 'p', 'e']
        starting_position: [0, 50]
        deterministic: ['y', 'n']
        include:
          - elements: 10
          - simulation: 'y'
        exclude:
          - agent_type: 'e'
            deterministic: 'n'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: pip install cap6635
      - name: Clean
        run: >
          python hw1_dynamic_programming.py ${{matrix.elements}}
          ${{matrix.agent_type}} ${{matrix.deterministic}}
          ${{matrix.simulation}} ${{matrix.starting_position}}
      - name: Animation Output
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: hw1
          path: |
            *.png
            *.gif

  q_learning:
    name: Maze Runner (q-learning)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent_type: ['q', 's']
        starting_position: [0, 30, 9, 50]
        deterministic: ['y']
        include:
          - elements: 10
          - simulation: 'y'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: pip install cap6635
      - name: Clean
        run: >
          python hw2_sarsa.py ${{matrix.elements}}
          ${{matrix.agent_type}} ${{matrix.deterministic}}
          ${{matrix.simulation}} ${{matrix.starting_position}}
      - name: Animation Output
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: hw2
          path: |
            *.png
            *.gif
